import 'package:floor/floor.dart';

@entity
class PM25 {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  //The carbohydrates content of the meal
  final double value;

  //When the meal occured
  final DateTime dateTime;

  //Default constructor
  PM25(this.id, this.value, this.dateTime);
}//Pms